GET http://localhost:3000 HTTP/1.1
###
//Thiss will generate your access token
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "cyril",
    "password": "cyril123",
    "role": "admin"
}
###
GET http://localhost:3000/login/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer insert_your_accessToken
###